export default {
    "APP_UPDT_STR_FULFLMNT_CONFIG": "APP_UPDT_STR_FULFLMNT_CONFIG",
    "APP_UPDT_ECOM_INV_CONFIG": "APP_UPDT_ECOM_INV_CONFIG",
    "APP_UNPACK_ORDER": "APP_UNPACK_ORDER",
    "APP_RECYCLE_ORDER": "APP_RECYCLE_ORDER",
}