/**
 * App actions mapped to the server permissions they require.
 *
 * Views, components and routes should always refer to an action from this file instead of
 * hardcoding a server permission, so that a permission change is a one line change here.
 *
 * The value is the permission expression evaluated by `hasPermission` of the user store.
 * It supports the `OR` and `AND` operators, and an empty value means the action is allowed
 * for every logged in user.
 */
export default {
  APP_OPEN_ORDERS_VIEW: "",
  APP_IN_PROGRESS_ORDERS_VIEW: "",
  APP_COMPLETED_ORDERS_VIEW: "",
  APP_ORDER_DETAIL_VIEW: "",
  APP_SHIPMENT_DETAIL_VIEW: "",
  APP_TRANSFER_ORDERS_VIEW: "ORD_TRANSFER_ORDER_VIEW OR ORD_TRANSFER_ORDER_ADMIN",
  APP_TRANSFER_ORDER_DETAIL_VIEW: "ORD_TRANSFER_ORDER_VIEW OR ORD_TRANSFER_ORDER_ADMIN",
  APP_TRANSFER_ORDER_CANCEL: "ORD_TRANSFER_ORDER_CANCEL",
  APP_STOREFULFILLMENT_ADMIN: "STOREFULFILLMENT_ADMIN",
  APP_REJECTION_REASONS_VIEW: "STOREFULFILLMENT_ADMIN",
  APP_REJECTIONS_VIEW: "STOREFULFILLMENT_ADMIN",
  APP_ORDER_LOOKUP_VIEW: "FF_ORDER_LOOKUP_VIEW",
  APP_INVOICING_STATUS_VIEW: "FF_INVOICING_STATUS_VIEW",
  APP_CARRIERS_VIEW: "CARRIER_SETUP_VIEW",
  APP_CARRIERS_CREATE: "CARRIER_SETUP_VIEW",
  APP_SHIP_ORDER: "COMMON_ADMIN OR FF_SHIP_NOW",
  APP_FORCE_SHIP_ORDER: "COMMON_ADMIN",
  APP_UNPACK_ORDER: "COMMON_ADMIN OR SF_UNLOCK_ORDER",
  APP_RECYCLE_ORDER: "COMMON_ADMIN OR STOREFULFILLMENT_ADMIN",
  APP_SHOW_ALL_PICKERS: "FULFILLMENT_VIEW_ALL_PICKERS",
  APP_ORDER_SHIPMENT_METHOD_UPDATE: "ORDER_SHIPMENT_METHOD_UPDATE",
  APP_PRODUCT_IDENTIFIER_UPDATE: "STOREFULFILLMENT_ADMIN",
  APP_BARCODE_IDENTIFIER_UPDATE: "COMMON_ADMIN",
  APP_UPDT_STR_FULFLMNT_CONFIG: "COMMON_ADMIN",
  APP_UPDT_ECOM_INV_CONFIG: "COMMON_ADMIN",
  APP_UPDT_FULFILL_FORCE_SCAN_CONFIG: "COMMON_ADMIN",
  APP_PARTIAL_ORDER_REJECTION_CONFIG_UPDATE: "COMMON_ADMIN",
  APP_COLLATERAL_REJECTION_CONFIG_UPDATE: "COMMON_ADMIN",
  APP_AFFECT_QOH_CONFIG_UPDATE: "COMMON_ADMIN",
  APP_COMMERCE_VIEW: "COMMERCEUSER_VIEW"
} as const satisfies Record<string, string>
