export default {
    "APP_OPEN_ORDERS_VIEW": "",
    "APP_IN_PROGRESS_ORDERS_VIEW": "",
    "APP_COMPLETED_ORDERS_VIEW": "",
    "APP_EXIM_VIEW": "",
    "APP_UPLOAD_IMPORT_ORDERS_VIEW": "",
    "APP_DOWNLOAD_PACKED_ORDERS_VIEW": "",
    "APP_UPDT_STR_FULFLMNT_CONFIG": "COMMON_ADMIN",
    "APP_UPDT_ECOM_INV_CONFIG": "COMMON_ADMIN",
    "APP_UNPACK_ORDER": "COMMON_ADMIN",
    "APP_RECYCLE_ORDER": "COMMON_ADMIN",
    "APP_STOREFULFILLMENT_ADMIN": "STOREFULFILLMENT_ADMIN",
    "APP_FORCE_SHIP_ORDER": "COMMON_ADMIN"
} as any