export const SN_REJECTION = 'rejection'
export const REJECTION_REJECTED_ITEMS_UPDATED = SN_REJECTION + '/REJECTED_ITEMS_UPDATED'
export const REJECTION_USED_REASONS_UPDATED = SN_REJECTION + '/USED_REASONS_UPDATED'
export const REJECTION_REJECTED_ORDERS_UPDATED = SN_REJECTION + '/REJECTION_REJECTED_ORDERS_UPDATED'
