export const SN_ORDER = 'transferorder'
export const ORDER_CURRENT_UPDATED = SN_ORDER + '/CURRENT_UPDATED'
export const ORDER_TRANSFER_QUERY_UPDATED = SN_ORDER + '/TRANSFER_QUERY_UPDATED'
export const ORDER_TRANSFER_UPDATED = SN_ORDER + '/TRANSFER_UPDATED'
export const ORDER_TRANSFER_CLEARED = SN_ORDER + '/TRANSFER_CLEARED'
export const ORDER_CURRENT_SHIPMENT_UPDATED = SN_ORDER + '/CURRENT_SHIPMENT_UPDATED'
export const ORDER_CURRENT_SHIPMENT_CLEARED = SN_ORDER + '/CURRENT_SHIPMENT_CLEARED'

